---
title: "Homework 1"
author: "Dhwani Kirankumar Trivedi, Ankita Dodhiyal and Miraj Bhimani"
date: "9/18/2021"
output: html_document
---


```{r}
#Question 1.1
df_fm <- read.csv("/Users/dhwani/Desktop/Data/fm.csv")
df_fm

#calculating total number of farmer markets in US
total_fm <- length(df_fm$FMID)
total_fm
```

```{r}
#Question 1.2
data=read.csv("/Users/dhwani/Desktop/Data/fm.csv")
print(head(df_fm))
states=c("")
states=c(unique(df_fm[,"State"]))

print(states)
counts=rep(0,53)
print(counts)
df=data.frame(states,counts)
colnames(df)=c("states","count")
for (state in df_fm[,"State"])
{
  df[df$states==state,]["count"]=df[df$states==state,]["count"]+1
}
df <-df[order(-df$count),]
#df <- sort(df$states, decreasing = TRUE )
print(df)
```

```{r}
#Question 1.3
data=read.csv("/Users/dhwani/Desktop/Data/fm.csv")
print(head(data))
df_mass <- data[data$State == "Massachusetts",]
df_mass
cities=c("")
cities = c(unique(df_mass[,"city"]))
print(cities)
counts=rep(0,223)
print(counts)
df=data.frame(cities,counts)
colnames(df)=c("cities","count")
print(colnames(df))
for (citys in df_mass[,"city"])
{
  df[df$cities==citys,]["count"]=df[df$cities==citys,]["count"]+1
}
df <-df[order(-df$count),]
#df <- sort(df$states, decreasing = TRUE )
print(df)
head(df,5)
```

```{r}
# Question 1.4 
#Top 5 states that offer coffee

df_Coffee <- df_fm[df_fm$Coffee == "Y",]
df <- table(df_Coffee$State)
df
df_c_y <- sort(df, decreasing = TRUE)
head(df_c_y,5)
```

```{r}
library(stringr)

wine_data <- read.csv('/Users/dhwani/Desktop/Data/wine_data.csv')
wine20<- str_to_lower(wine_data$designation)

ans2<- grep('20 y|20-y', wine20)


print(length(ans2))
```


```{r}
kw_data=read.csv("kw_data.csv")
data=kw_data
colnames(data)=c("title","k1","k2","k3","k4","k5","k6","k7","k8","k9","k10","k11","k12")
data=data[-1,]
kw=data[,-1]
corpus=c(kw$k1,kw$k2,kw$k3,kw$k4,kw$k5,kw$k6,kw$k7,kw$k8,kw$k9,kw$k10,kw$k11,kw$k12)
print(length(corpus))
corpus=corpus[corpus!=""]
corpus=tolower(corpus)
corpus=unique(corpus)

kw=read.csv("data.csv")
adj=matrix(0,nrow=248,ncol=248)
colnames(adj) <- corpus
rownames(adj) <- corpus
adj

for (text in kw$conc)
 
{
  for (row in 1:248)
  {
    for (col in row:248)
    {
     
      if(str_contains(text,corpus[row]) & str_contains(text,corpus[col]))
      {
        print("match")
        adj[row,col]=(adj[row,col])+1
      }
    }
  }
}
print(adj)

```
```{r}
#All the questions have been solved equally by all the teammates
```

